file_format: "1"
id: wackymxter
name: WACKYMXTER
type: shield
url: https://github.com/willwng/WackyMXter
requires: [xiao_ble]
features:
  - keys
  - encoder
siblings:
  - wackymxter_left
  - wackymxter_right
